dist: xenial
branches:
  only:
  - master
language: node_js
node_js:
- 10
cache: npm
jobs:
  include:
  - script:
    - cd website && npm install
    - npm run test
  - stage: deploy
    script:
      - cd website && npm install
      - gulp deploy
stages:
- name: test
  if: type = pull_request
- name: deploy
  if: branch = master
notifications:
  email:
    recipients:
    - patrique.legault@gmail.com